version: '3.8'

services:
  spark-worker:
    image: bitnami/spark:latest
    hostname: spark-worker
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${MASTER_IP}:7077
      - SPARK_WORKER_MEMORY=1G
    networks:
      - spark-network

networks:
  spark-network:
    external: true
